### ISSUE TITLE
Img Tag will not display once we upload image

### ISSUE THREAD

**Issue by baby-in-magento** [AlenToma/Canvas-Mask#1]
This is wonderfull plugin, but once user upload image, then it will not create img tag, so user can't zoom or rotate the image as mentioned in this below link , so please update the code with img tag.....

https://stackoverflow.com/questions/55652733/zoom-the-user-uploaded-image-onclick-button

**Comment by AlenToma** [comment]
Sorry really dont have the time. I have already provided you with a rotation solution at
https://jsfiddle.net/uf4h6x08/
This plugin is to only provide a basic understanding of mask and drag in the canvas. Any additional changes you will have to provided on your own. So take this plugin and change it howver you like and add all other changes that link have provided.

**Comment by baby-in-magento** [comment]
Thanks a lot, i got solution for zoom : https://codepen.io/kidsdial/pen/gJJEyN
